"""Catálogo de APIs e blocos de migração da Plataforma APS.

Arquivo atualizado pela v19 para incluir o bloco Dados Abertos/MS — Regionalização de Saúde.
"""

API_CATALOG = [{'codigo': 'ibge_municipios',
  'grupo': 'IBGE',
  'nome': 'Municípios de Mato Grosso',
  'descricao': 'Lista oficial de municípios, códigos e informações territoriais básicas.',
  'funcao_carregar': 'carregar_municipios_ibge_mt',
  'funcao_testar': None,
  'tipo_base': None,
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_municipios_ibge_mt',
  'fallback_legacy': True},
 {'codigo': 'ibge_regioes_geograficas',
  'grupo': 'IBGE',
  'nome': 'Regiões geográficas IBGE',
  'descricao': 'Regiões imediatas/intermediárias vinculadas aos municípios.',
  'funcao_carregar': 'carregar_regioes_geograficas_ibge_mt',
  'funcao_testar': None,
  'tipo_base': 'indicadores',
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_regioes_geograficas_ibge_mt',
  'fallback_legacy': True},
 {'codigo': 'ibge_distritos',
  'grupo': 'IBGE',
  'nome': 'Distritos municipais',
  'descricao': 'Distritos oficiais por município.',
  'funcao_carregar': 'carregar_distritos_ibge_mt',
  'funcao_testar': None,
  'tipo_base': 'indicadores',
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_distritos_ibge_mt',
  'fallback_legacy': True},
 {'codigo': 'ibge_populacao',
  'grupo': 'IBGE/SIDRA',
  'nome': 'População estimada',
  'descricao': 'População residente estimada por município.',
  'funcao_carregar': 'carregar_populacao_sidra_mt',
  'funcao_testar': None,
  'tipo_base': 'populacao',
  'kwargs_carregar': {'ano': 2025},
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_populacao_sidra_mt',
  'fallback_legacy': True},
 {'codigo': 'ibge_area_densidade',
  'grupo': 'IBGE/SIDRA',
  'nome': 'Área territorial e densidade',
  'descricao': 'Área territorial e densidade demográfica municipal.',
  'funcao_carregar': 'carregar_area_densidade_sidra_mt',
  'funcao_testar': None,
  'tipo_base': 'indicadores',
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_area_densidade_sidra_mt',
  'fallback_legacy': True},
 {'codigo': 'ibge_urbano_rural',
  'grupo': 'IBGE/SIDRA',
  'nome': 'Perfil urbano/rural',
  'descricao': 'Perfil territorial urbano/rural do Censo 2022.',
  'funcao_carregar': 'carregar_urbano_rural_sidra_mt',
  'funcao_testar': None,
  'tipo_base': 'indicadores',
  'kwargs_carregar': {'ano_censo': 2022},
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_urbano_rural_sidra_mt',
  'fallback_legacy': True},
 {'codigo': 'ibge_demografia_9515',
  'grupo': 'IBGE/SIDRA',
  'nome': 'Demografia — envelhecimento e idade mediana',
  'descricao': 'Indicadores demográficos estruturais do Censo 2022.',
  'funcao_carregar': 'carregar_indicadores_demograficos_sidra_mt',
  'funcao_testar': None,
  'tipo_base': 'indicadores',
  'kwargs_carregar': {'ano_censo': 2022},
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_indicadores_demograficos_sidra_mt',
  'fallback_legacy': True},
 {'codigo': 'ibge_alfabetizacao_9543',
  'grupo': 'IBGE/SIDRA',
  'nome': 'Taxa de alfabetização',
  'descricao': 'Taxa de alfabetização da população de 15 anos ou mais.',
  'funcao_carregar': 'carregar_alfabetizacao_sidra_mt',
  'funcao_testar': None,
  'tipo_base': 'indicadores',
  'kwargs_carregar': {'ano_censo': 2022},
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_alfabetizacao_sidra_mt',
  'fallback_legacy': True},
 {'codigo': 'ibge_instrucao_10061',
  'grupo': 'IBGE/SIDRA',
  'nome': 'Nível de instrução',
  'descricao': 'Nível de instrução da população de 25 anos ou mais.',
  'funcao_carregar': 'carregar_nivel_instrucao_sidra_mt',
  'funcao_testar': None,
  'tipo_base': 'indicadores',
  'kwargs_carregar': {'ano_censo': 2022},
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_nivel_instrucao_sidra_mt',
  'fallback_legacy': True},
 {'codigo': 'ibge_renda_censo',
  'grupo': 'IBGE/SIDRA',
  'nome': 'Renda — Censo 2022',
  'descricao': 'Rendimento domiciliar per capita e vulnerabilidade de renda.',
  'funcao_carregar': 'carregar_renda_censo_sidra_mt',
  'funcao_testar': 'testar_renda_ibge',
  'tipo_base': 'vulnerabilidade',
  'kwargs_carregar': {'ano_censo': 2022},
  'kwargs_testar': {'ano_censo': 2022},
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_renda_censo_sidra_mt',
  'fallback_legacy': True},
 {'codigo': 'ibge_deficiencia_autismo',
  'grupo': 'IBGE/SIDRA',
  'nome': 'Deficiência e autismo',
  'descricao': 'Camada populacional de deficiência/TEA quando disponível no SIDRA.',
  'funcao_carregar': 'carregar_deficiencia_autismo_ibge_mt',
  'funcao_testar': 'testar_deficiencia_autismo_ibge',
  'tipo_base': 'vulnerabilidade',
  'kwargs_carregar': {'ano_censo': 2022},
  'kwargs_testar': {'ano_censo': 2022},
  'status_migracao': 'Aguardando migração específica; usar legacy se disponível',
  'executor': 'legacy',
  'fallback_legacy': True},
 {'codigo': 'ibge_saneamento',
  'grupo': 'IBGE/SIDRA',
  'nome': 'Saneamento',
  'descricao': 'Indicadores municipais de saneamento do Censo 2022.',
  'funcao_carregar': 'carregar_saneamento_sidra_mt',
  'funcao_testar': None,
  'tipo_base': 'vulnerabilidade',
  'kwargs_carregar': {'ano_censo': 2022},
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_saneamento_sidra_mt',
  'fallback_legacy': True},
 {'codigo': 'ibge_povos_tradicionais',
  'grupo': 'IBGE/SIDRA',
  'nome': 'Povos indígenas e quilombolas',
  'descricao': 'Populações tradicionais agregadas por município, quando disponíveis.',
  'funcao_carregar': 'carregar_povos_tradicionais_ibge_mt',
  'funcao_testar': 'testar_povos_tradicionais_ibge',
  'tipo_base': 'vulnerabilidade',
  'kwargs_carregar': {'ano_censo': 2022},
  'kwargs_testar': {'ano_censo': 2022},
  'status_migracao': 'Migração v04: executor nativo com fallback legacy',
  'executor': 'nativo',
  'modulo_nativo': 'services.api_ibge_sidra',
  'funcao_nativa': 'carregar_povos_tradicionais_ibge_mt',
  'fallback_legacy': True},
 {'codigo': 'dadosabertos_regioes_saude',
  'grupo': 'Dados Abertos/MS',
  'nome': 'Regiões de Saúde e Macrorregiões',
  'descricao': 'Base de regionalização do SUS com vínculo município, região de saúde e macrorregião, para validar a '
               'regionalização usada pelo sistema.',
  'funcao_carregar': 'carregar_regioes_saude_dadosabertos_mt',
  'funcao_testar': None,
  'tipo_base': 'indicadores',
  'status_migracao': 'Migração v19: conector nativo via Dados Abertos/MS com validação contra municípios MT',
  'executor': 'nativo',
  'fallback_legacy': True,
  'modulo_nativo': 'services.api_dadosabertos_ms',
  'funcao_nativa': 'carregar_regioes_saude_dadosabertos_mt'},
 {'codigo': 'cnes_estabelecimentos_ubs',
  'grupo': 'CNES',
  'nome': 'Estabelecimentos/UBS',
  'descricao': 'Estabelecimentos de saúde filtrados/classificados para APS/UBS.',
  'funcao_carregar': 'carregar_cnes_estabelecimentos_ubs_mt',
  'funcao_testar': 'testar_cnes_estabelecimentos_dadosabertos',
  'tipo_base': 'estabelecimentos',
  'status_migracao': 'Migração v07: executor nativo via ponte legacy controlada',
  'executor': 'nativo',
  'fallback_legacy': True,
  'modulo_nativo': 'services.api_cnes_datasus',
  'funcao_nativa': 'carregar_cnes_estabelecimentos_ubs_mt'},
 {'codigo': 'cnes_equipes_ine',
  'grupo': 'CNES',
  'nome': 'Equipes APS/INE — tipos 70, 71, 72, 73, 74 e 76',
  'descricao': 'Equipes APS válidas vinculadas ao CNES/INE, com classificação por código de tipo de equipe.',
  'funcao_carregar': 'carregar_cnes_equipes_ine_mt',
  'funcao_testar': None,
  'tipo_base': 'equipes',
  'status_migracao': 'Migração v08: equipes APS/INE via ponte legacy de georreferenciamento',
  'executor': 'nativo',
  'fallback_legacy': False,
  'modulo_nativo': 'services.api_cnes_profissionais',
  'funcao_nativa': 'carregar_cnes_equipes_ine_mt'},
 {'codigo': 'cnes_profissionais_equipes',
  'grupo': 'CNES',
  'nome': 'Profissionais vinculados às equipes CNES/INE',
  'descricao': 'Profissionais do arquivo ProfissionaisEquipesBrasil.txt, vinculados de forma anonimizada às equipes '
               'CNES/INE.',
  'funcao_carregar': 'carregar_cnes_profissionais_equipes_mt',
  'funcao_testar': None,
  'tipo_base': 'profissionais',
  'status_migracao': 'Migração v08.4: profissionais do EQUIPES BRASIL via ProfissionaisEquipesBrasil.txt',
  'executor': 'nativo',
  'fallback_legacy': False,
  'modulo_nativo': 'services.api_cnes_profissionais',
  'funcao_nativa': 'carregar_cnes_profissionais_equipes_mt'},
 {'codigo': 'cnes_leitos',
  'grupo': 'CNES',
  'nome': 'Leitos SUS',
  'descricao': 'Leitos e contexto hospitalar de apoio territorial.',
  'funcao_carregar': 'carregar_leitos_sus_mt',
  'funcao_testar': 'testar_leitos_sus_dadosabertos',
  'tipo_base': 'leitos',
  'status_migracao': 'Migração v07: executor nativo via ponte legacy controlada',
  'executor': 'nativo',
  'fallback_legacy': True,
  'modulo_nativo': 'services.api_cnes_datasus',
  'funcao_nativa': 'carregar_leitos_sus_mt'},
 {'codigo': 'datasus_sinasc',
  'grupo': 'DATASUS',
  'nome': 'SINASC — nascidos vivos',
  'descricao': 'Nascidos vivos por município, agregados para pressão assistencial.',
  'funcao_carregar': 'carregar_sinasc_nascidos_vivos_mt',
  'funcao_testar': 'testar_sinasc_dadosabertos',
  'tipo_base': 'indicadores',
  'kwargs_carregar': {'ano': 2024},
  'kwargs_testar': {'ano': 2024},
  'status_migracao': 'Migração v07: executor nativo via ponte legacy controlada',
  'executor': 'nativo',
  'fallback_legacy': True,
  'modulo_nativo': 'services.api_cnes_datasus',
  'funcao_nativa': 'carregar_sinasc_nascidos_vivos_mt'},
 {'codigo': 'datasus_sim',
  'grupo': 'DATASUS',
  'nome': 'SIM — mortalidade',
  'descricao': 'Mortalidade e mortalidade infantil por município.',
  'funcao_carregar': 'carregar_sim_mortalidade_mt',
  'funcao_testar': 'testar_sim_dadosabertos',
  'tipo_base': 'indicadores',
  'kwargs_carregar': {'ano': 2024},
  'kwargs_testar': {'ano': 2024},
  'status_migracao': 'Migração v07: executor nativo via ponte legacy controlada',
  'executor': 'nativo',
  'fallback_legacy': True,
  'modulo_nativo': 'services.api_cnes_datasus',
  'funcao_nativa': 'carregar_sim_mortalidade_mt'},
 {'codigo': 'inep_censo_escolar',
  'grupo': 'INEP',
  'nome': 'Censo Escolar — escolas e territorialidade',
  'descricao': 'Escolas totais, urbanas, rurais, indígenas, quilombolas, educação especial/AEE e matrículas quando '
               'disponíveis.',
  'funcao_carregar': 'carregar_censo_escolar_inep_mt',
  'funcao_testar': 'testar_inep_censo_escolar',
  'tipo_base': 'indicadores',
  'kwargs_carregar': {'ano': 2024},
  'kwargs_testar': {'ano': 2024},
  'status_migracao': 'Migração v16: conector nativo INEP/Microdados com staging em indicadores_municipais',
  'executor': 'nativo',
  'fallback_legacy': False,
  'modulo_nativo': 'services.api_inep',
  'funcao_nativa': 'carregar_censo_escolar_inep_mt'},
 {'codigo': 'inep_educacao_especial',
  'grupo': 'INEP',
  'nome': 'Educação Especial/AEE — recorte do Censo Escolar',
  'descricao': 'Recorte de escolas com educação especial/AEE a partir da mesma base do Censo Escolar.',
  'funcao_carregar': 'carregar_educacao_especial_inep_mt',
  'funcao_testar': 'testar_educacao_especial_inep',
  'tipo_base': 'indicadores',
  'kwargs_carregar': {'ano': 2024},
  'kwargs_testar': {'ano': 2024},
  'status_migracao': 'Migração v16: conector nativo INEP/Microdados; uso complementar',
  'executor': 'nativo',
  'fallback_legacy': False,
  'modulo_nativo': 'services.api_inep',
  'funcao_nativa': 'carregar_educacao_especial_inep_mt'},
 {'codigo': 'ibge_censo2022_povos_tradicionais',
  'grupo': 'IBGE/Censo 2022',
  'nome': 'Populações indígena e quilombola',
  'descricao': 'População indígena e população quilombola por município, como camada de equidade territorial.',
  'funcao_carregar': 'carregar_povos_tradicionais_censo2022_mt',
  'funcao_testar': 'testar_povos_tradicionais_censo2022',
  'tipo_base': 'indicadores',
  'kwargs_carregar': {'ano_censo': 2022},
  'kwargs_testar': {'ano_censo': 2022},
  'status_migracao': 'Migração v17: conector nativo IBGE/SIDRA Censo 2022; entra em staging/auditoria.',
  'executor': 'nativo',
  'fallback_legacy': False,
  'modulo_nativo': 'services.api_ibge_censo2022',
  'funcao_nativa': 'carregar_povos_tradicionais_censo2022_mt'},
 {'codigo': 'ibge_censo2022_deficiencia_autismo',
  'grupo': 'IBGE/Censo 2022',
  'nome': 'Pessoas com deficiência e autismo',
  'descricao': 'Pessoas com deficiência e pessoas diagnosticadas com TEA por município, quando disponível no SIDRA.',
  'funcao_carregar': 'carregar_deficiencia_autismo_censo2022_mt',
  'funcao_testar': 'testar_deficiencia_autismo_censo2022',
  'tipo_base': 'indicadores',
  'kwargs_carregar': {'ano_censo': 2022},
  'kwargs_testar': {'ano_censo': 2022},
  'status_migracao': 'Migração v17: conector nativo IBGE/SIDRA Censo 2022; entra em staging/auditoria.',
  'executor': 'nativo',
  'fallback_legacy': False,
  'modulo_nativo': 'services.api_ibge_censo2022',
  'funcao_nativa': 'carregar_deficiencia_autismo_censo2022_mt'},
 {'codigo': 'mds_cadunico',
  'grupo': 'MDS',
  'nome': 'Cadastro Único — famílias, pessoas, pobreza e extrema pobreza',
  'descricao': 'Camada socioassistencial agregada por município: famílias/pessoas cadastradas e recortes de '
               'pobreza/extrema pobreza.',
  'funcao_carregar': 'carregar_mds_cadunico_mt',
  'funcao_testar': None,
  'tipo_base': 'vulnerabilidade',
  'status_migracao': 'Migração v12: conector nativo com fallback por upload manual em data/uploads/mds',
  'executor': 'nativo',
  'fallback_legacy': False,
  'modulo_nativo': 'services.api_mds',
  'funcao_nativa': 'carregar_mds_cadunico_mt'},
 {'codigo': 'mds_bolsa_familia',
  'grupo': 'MDS',
  'nome': 'Bolsa Família — famílias beneficiárias e valor repassado',
  'descricao': 'Programa Bolsa Família agregado por município, como insumo de vulnerabilidade social.',
  'funcao_carregar': 'carregar_mds_bolsa_familia_mt',
  'funcao_testar': None,
  'tipo_base': 'vulnerabilidade',
  'status_migracao': 'Migração v12: conector nativo com fallback por upload manual em data/uploads/mds',
  'executor': 'nativo',
  'fallback_legacy': False,
  'modulo_nativo': 'services.api_mds',
  'funcao_nativa': 'carregar_mds_bolsa_familia_mt'},
 {'codigo': 'mds_bpc',
  'grupo': 'MDS',
  'nome': 'BPC — total, idoso e pessoa com deficiência',
  'descricao': 'Benefício de Prestação Continuada agregado por município, como camada complementar de vulnerabilidade.',
  'funcao_carregar': 'carregar_mds_bpc_mt',
  'funcao_testar': None,
  'tipo_base': 'vulnerabilidade',
  'status_migracao': 'Migração v12: conector nativo com fallback por upload manual em data/uploads/mds',
  'executor': 'nativo',
  'fallback_legacy': False,
  'modulo_nativo': 'services.api_mds',
  'funcao_nativa': 'carregar_mds_bpc_mt'},
 {'codigo': 'portal_transparencia_bpc',
  'grupo': 'Portal da Transparência/MDS',
  'nome': 'BPC',
  'descricao': 'Benefícios BPC agregados por município.',
  'funcao_carregar': 'carregar_bpc_portal_transparencia_mt',
  'funcao_testar': 'testar_bpc_portal_transparencia',
  'tipo_base': 'vulnerabilidade',
  'status_migracao': 'Pronto para testar',
  'executor': 'legacy',
  'fallback_legacy': True},
 {'codigo': 'portal_transparencia_bolsa_familia',
  'grupo': 'Portal da Transparência/MDS',
  'nome': 'Bolsa Família',
  'descricao': 'Benefícios do Novo Bolsa Família agregados por município.',
  'funcao_carregar': 'carregar_bolsa_familia_portal_transparencia_mt',
  'funcao_testar': 'testar_bolsa_familia_portal_transparencia',
  'tipo_base': 'vulnerabilidade',
  'status_migracao': 'Pode exigir ajuste de endpoint',
  'executor': 'legacy',
  'fallback_legacy': True},
 {'codigo': 'pni_doses',
  'grupo': 'Dados Abertos/MS',
  'nome': 'PNI — doses aplicadas',
  'descricao': 'Vacinação por município. Mantido no catálogo, mas pode exigir fallback por bloqueio 403.',
  'funcao_carregar': 'carregar_pni_doses_mt',
  'funcao_testar': 'testar_pni_doses_dadosabertos',
  'tipo_base': 'indicadores',
  'kwargs_carregar': {'ano': 2025},
  'kwargs_testar': {'ano': 2025},
  'status_migracao': 'Instável / validar depois',
  'executor': 'legacy',
  'fallback_legacy': True}
,
 {'codigo': 'dadosabertos_ms_hospitais_leitos',
  'grupo': 'Dados Abertos/MS',
  'nome': 'Hospitais e Leitos — JSON anual',
  'descricao': 'Base do Portal de Dados Abertos do SUS com estabelecimentos hospitalares, leitos gerais/complementares e informações de contato por competência anual.',
  'funcao_carregar': 'carregar_hospitais_leitos_ms_mt',
  'funcao_testar': 'testar_hospitais_leitos_ms',
  'tipo_base': 'leitos',
  'kwargs_carregar': {'ano': 2026},
  'kwargs_testar': {'ano': 2026},
  'status_migracao': 'Migração v20: conector nativo do conjunto Hospitais e Leitos do Portal de Dados Abertos do SUS',
  'executor': 'nativo',
  'fallback_legacy': False,
  'modulo_nativo': 'services.api_hospitais_leitos_ms',
  'funcao_nativa': 'carregar_hospitais_leitos_ms_mt'}
]

API_BLOCKS = [{'codigo': 'bloco_ibge_territorial',
  'nome': 'IBGE/SIDRA — Base territorial mínima',
  'descricao': 'Municípios, distritos, regiões geográficas, população e área/densidade. É o primeiro bloco para '
               'estruturar o georreferenciamento e a base municipal.',
  'apis': ['ibge_municipios', 'ibge_distritos', 'ibge_regioes_geograficas', 'ibge_populacao', 'ibge_area_densidade']},
 {'codigo': 'bloco_dadosabertos_ms_regionalizacao',
  'nome': 'Dados Abertos/MS — Regionalização de Saúde',
  'descricao': 'Carrega a base de Regiões de Saúde e Macrorregiões do SUS para comparar com a regionalização canônica '
               'usada pelo sistema.',
  'apis': ['dadosabertos_regioes_saude']},
 {'codigo': 'bloco_ibge_socioeconomico',
  'nome': 'IBGE/SIDRA — Vulnerabilidade e perfil populacional',
  'descricao': 'Perfil urbano/rural, demografia, alfabetização, instrução, renda, saneamento e povos tradicionais. '
               'Bloco de apoio ao diagnóstico territorial.',
  'apis': ['ibge_urbano_rural',
           'ibge_demografia_9515',
           'ibge_alfabetizacao_9543',
           'ibge_instrucao_10061',
           'ibge_renda_censo',
           'ibge_saneamento',
           'ibge_povos_tradicionais']},
 {'codigo': 'bloco_cnes_datasus',
  'nome': 'CNES/DATASUS — UBS, leitos e eventos vitais',
  'descricao': 'Estabelecimentos/UBS, leitos SUS, SINASC e SIM. Primeira camada CNES/DATASUS para enriquecer a base '
               'municipal e o diagnóstico territorial.',
  'apis': ['cnes_estabelecimentos_ubs', 'cnes_leitos', 'datasus_sinasc', 'datasus_sim']},
 {'codigo': 'bloco_cnes_equipes_ine',
  'nome': 'CNES — Equipes APS/INE por código',
  'descricao': 'Carrega equipes APS e profissionais vinculados ao CNES/INE, alimentando totais por código e total de '
               'profissionais.',
  'apis': ['cnes_equipes_ine', 'cnes_profissionais_equipes']},
 {'codigo': 'bloco_inep_educacao',
  'nome': 'INEP — Censo Escolar e territorialidade',
  'descricao': 'Escolas totais, urbanas, rurais, indígenas, quilombolas e educação especial/AEE. Entra como '
               'staging/auditoria antes de virar indicador oficial.',
  'apis': ['inep_censo_escolar']},
 {'codigo': 'bloco_ibge_censo2022_populacoes_especificas',
  'nome': 'IBGE Censo 2022 — Populações específicas e equidade',
  'descricao': 'População indígena, quilombola, pessoas com deficiência e pessoas diagnosticadas com autismo. Entra em '
               'staging/auditoria antes de alimentar indicador oficial.',
  'apis': ['ibge_censo2022_povos_tradicionais', 'ibge_censo2022_deficiencia_autismo']},
 {'codigo': 'bloco_dadosabertos_ms_hospitais_leitos',
  'nome': 'Dados Abertos/MS — Hospitais e Leitos',
  'descricao': 'Carrega o conjunto Hospitais e Leitos do Portal de Dados Abertos do SUS em JSON anual, filtrando Mato Grosso e importando como camada de leitos em auditoria.',
  'apis': ['dadosabertos_ms_hospitais_leitos']},

 {'codigo': 'bloco_mds_socioassistencial',
  'nome': 'MDS — Camada socioassistencial',
  'descricao': 'Cadastro Único, Bolsa Família e BPC agregados por município. Os dados entram como insumos brutos para '
               'análise de vulnerabilidade, sem gerar índice automático neste momento.',
  'apis': ['mds_cadunico', 'mds_bolsa_familia', 'mds_bpc']}]

# Migração v21 — IBGE Malhas Geográficas municipais de Mato Grosso.
# Mantida como append defensivo para evitar conflitos com a lista principal do catálogo.
if not any(item.get("codigo") == "ibge_malhas_geograficas_mt" for item in API_CATALOG):
    API_CATALOG.append({
        "codigo": "ibge_malhas_geograficas_mt",
        "grupo": "IBGE/Malhas Geográficas",
        "nome": "Malhas geográficas municipais — MT",
        "descricao": "GeoJSON municipal de Mato Grosso via API oficial do IBGE, com geometria, centroide aproximado e bounding box para mapas e vazios territoriais.",
        "funcao_carregar": "carregar_malhas_geograficas_ibge_mt",
        "funcao_testar": "testar_malhas_geograficas_ibge_mt",
        "tipo_base": "malhas_geograficas",
        "status_migracao": "Migração v21: conector nativo IBGE Malhas Geográficas, API-only, sem upload manual.",
        "executor": "nativo",
        "fallback_legacy": False,
        "modulo_nativo": "services.api_ibge_malhas",
        "funcao_nativa": "carregar_malhas_geograficas_ibge_mt",
    })

if not any(item.get("codigo") == "bloco_ibge_malhas_geograficas" for item in API_BLOCKS):
    API_BLOCKS.append({
        "codigo": "bloco_ibge_malhas_geograficas",
        "nome": "IBGE — Malhas Geográficas Municipais",
        "descricao": "Carrega a malha territorial municipal de Mato Grosso em GeoJSON, permitindo mapas, polígonos municipais, centroides aproximados e análise de vazios territoriais.",
        "apis": ["ibge_malhas_geograficas_mt"],
    })



# Migração v22 — CNES Estabelecimentos gerais via Portal de Dados Abertos do SUS.
# Camada separada da APS/UBS para não contaminar os indicadores estruturais.
if not any(item.get("codigo") == "cnes_estabelecimentos_gerais" for item in API_CATALOG):
    API_CATALOG.append({
        "codigo": "cnes_estabelecimentos_gerais",
        "grupo": "CNES/Dados Abertos MS",
        "nome": "CNES — Estabelecimentos gerais de saúde",
        "descricao": "Relação geral dos estabelecimentos do CNES filtrada para Mato Grosso, via ZIP CSV oficial do Portal de Dados Abertos do SUS.",
        "funcao_carregar": "carregar_cnes_estabelecimentos_gerais_mt",
        "funcao_testar": "testar_cnes_estabelecimentos_gerais_mt",
        "tipo_base": "estabelecimentos_gerais",
        "status_migracao": "Migração v22: conector nativo API-only, sem upload manual, com gravação em tabela própria.",
        "executor": "nativo",
        "fallback_legacy": False,
        "modulo_nativo": "services.api_cnes_estabelecimentos_gerais",
        "funcao_nativa": "carregar_cnes_estabelecimentos_gerais_mt",
    })

if not any(item.get("codigo") == "bloco_cnes_estabelecimentos_gerais" for item in API_BLOCKS):
    API_BLOCKS.append({
        "codigo": "bloco_cnes_estabelecimentos_gerais",
        "nome": "CNES — Estabelecimentos gerais de saúde",
        "descricao": "Carrega a relação geral dos estabelecimentos CNES de Mato Grosso, preservando uma tabela separada da camada APS/UBS.",
        "apis": ["cnes_estabelecimentos_gerais"],
    })


# Migração v23 — IBGE/SIDRA PIB Municipal.
# Camada socioeconômica complementar para capacidade econômica municipal e análise territorial.
if not any(item.get("codigo") == "ibge_pib_municipal" for item in API_CATALOG):
    API_CATALOG.append({
        "codigo": "ibge_pib_municipal",
        "grupo": "IBGE/SIDRA",
        "nome": "PIB Municipal — PIB total e PIB per capita",
        "descricao": "PIB municipal a preços correntes e PIB per capita via tabela SIDRA 5938, filtrado para Mato Grosso. Entra como indicador socioeconômico complementar.",
        "funcao_carregar": "carregar_pib_municipal_ibge_mt",
        "funcao_testar": "testar_pib_municipal_ibge_mt",
        "tipo_base": "indicadores",
        "kwargs_carregar": {"periodo": "last"},
        "kwargs_testar": {"periodo": "last"},
        "status_migracao": "Migração v23: conector nativo SIDRA PIB Municipal, API-only, sem upload manual.",
        "executor": "nativo",
        "fallback_legacy": False,
        "modulo_nativo": "services.api_ibge_pib_municipal",
        "funcao_nativa": "carregar_pib_municipal_ibge_mt",
    })

if not any(item.get("codigo") == "bloco_ibge_pib_municipal" for item in API_BLOCKS):
    API_BLOCKS.append({
        "codigo": "bloco_ibge_pib_municipal",
        "nome": "IBGE/SIDRA — PIB Municipal",
        "descricao": "Carrega PIB municipal total e PIB per capita para compor leitura socioeconômica, capacidade econômica e desigualdades territoriais nos diagnósticos municipais.",
        "apis": ["ibge_pib_municipal"],
    })


# Migração v24 — Portal de Dados Abertos MT / CKAN.
# Inventário inicial para descobrir bases estaduais úteis antes de integrar conjuntos específicos.
if not any(item.get("codigo") == "dadosabertos_mt_catalogo_ckan" for item in API_CATALOG):
    API_CATALOG.append({
        "codigo": "dadosabertos_mt_catalogo_ckan",
        "grupo": "Dados Abertos MT / SEPLAG",
        "nome": "Catálogo CKAN — Dados Abertos MT",
        "descricao": "Inventário dos datasets e recursos do Portal de Dados Abertos de Mato Grosso, com classificação preliminar de relevância para APS. Não alimenta a Base Completa; serve para escolher próximas integrações estaduais.",
        "funcao_carregar": "carregar_catalogo_dadosabertos_mt",
        "funcao_testar": "testar_catalogo_dadosabertos_mt",
        "tipo_base": "catalogo_dados_mt",
        "status_migracao": "Migração v24: conector nativo CKAN package_search, API-only, camada de descoberta/inventário.",
        "executor": "nativo",
        "fallback_legacy": False,
        "modulo_nativo": "services.api_dadosabertos_mt",
        "funcao_nativa": "carregar_catalogo_dadosabertos_mt",
    })

if not any(item.get("codigo") == "bloco_dadosabertos_mt_catalogo" for item in API_BLOCKS):
    API_BLOCKS.append({
        "codigo": "bloco_dadosabertos_mt_catalogo",
        "nome": "Dados Abertos MT — Catálogo estadual CKAN",
        "descricao": "Mapeia os conjuntos publicados no portal estadual para identificar bases aproveitáveis na APS antes de criar conectores específicos.",
        "apis": ["dadosabertos_mt_catalogo_ckan"],
    })


# Migração v25 — Dados MT / SEPLAG — Explorador ICQV em Power BI.
# Esta é uma etapa de descoberta: localiza a ferramenta oficial ICQV e verifica se há endpoint reaproveitável.
if not any(item.get("codigo") == "dados_mt_icqv_explorador_powerbi" for item in API_CATALOG):
    API_CATALOG.append({
        "codigo": "dados_mt_icqv_explorador_powerbi",
        "grupo": "Dados MT / SEPLAG",
        "nome": "Explorador ICQV-MT — Power BI/Dados MT",
        "descricao": "Explora as páginas oficiais Dados MT e SEPLAG para localizar o painel ICQV-MT, extrair links Power BI e diagnosticar se há endpoint JSON/CSV reaproveitável. Não consolida dados municipais ainda.",
        "funcao_carregar": "carregar_explorador_icqv_dados_mt",
        "funcao_testar": "testar_explorador_icqv_dados_mt",
        "tipo_base": "dados_mt_icqv_explorador",
        "status_migracao": "Migração v25: conector exploratório API-only/HTML para ICQV-MT; etapa de descoberta antes de importação municipal.",
        "executor": "nativo",
        "fallback_legacy": False,
        "modulo_nativo": "services.api_dadosmt_icqv",
        "funcao_nativa": "carregar_explorador_icqv_dados_mt",
    })

if not any(item.get("codigo") == "bloco_dados_mt_icqv_explorador" for item in API_BLOCKS):
    API_BLOCKS.append({
        "codigo": "bloco_dados_mt_icqv_explorador",
        "nome": "Dados MT / SEPLAG — Explorador ICQV-MT",
        "descricao": "Localiza o produto ICQV-MT fora do CKAN estadual, registra os links do Power BI e verifica se há sinais de endpoint de dados aproveitável para futura integração.",
        "apis": ["dados_mt_icqv_explorador_powerbi"],
    })


# Migração v26 — Dados Abertos MT / INTERMAT — Assentamentos.
# Camada territorial para ruralidade, áreas de difícil acesso e vulnerabilidade assistencial.
if not any(item.get("codigo") == "dadosabertos_mt_assentamentos_intermt" for item in API_CATALOG):
    API_CATALOG.append({
        "codigo": "dadosabertos_mt_assentamentos_intermt",
        "grupo": "Dados Abertos MT / INTERMAT",
        "nome": "Assentamentos — INTERMAT/MT",
        "descricao": "Carrega a camada estadual de assentamentos rurais publicada no Portal de Dados Abertos MT. A base é territorial e serve para apoiar análises de ruralidade, distância, vazios assistenciais e priorização da APS.",
        "funcao_carregar": "carregar_assentamentos_intermt_mt",
        "funcao_testar": "testar_assentamentos_intermt_mt",
        "tipo_base": "dados_mt_assentamentos",
        "status_migracao": "Migração v26: conector nativo API-only para ZIP/SHP do INTERMAT; importa tabela própria, sem entrar automaticamente na Base Completa.",
        "executor": "nativo",
        "fallback_legacy": False,
        "modulo_nativo": "services.api_dadosabertos_mt_assentamentos",
        "funcao_nativa": "carregar_assentamentos_intermt_mt",
    })

if not any(item.get("codigo") == "bloco_dadosabertos_mt_assentamentos" for item in API_BLOCKS):
    API_BLOCKS.append({
        "codigo": "bloco_dadosabertos_mt_assentamentos",
        "nome": "Dados Abertos MT / INTERMAT — Assentamentos",
        "descricao": "Cria camada territorial estadual de assentamentos para análise de vulnerabilidade rural, vazios assistenciais e dificuldade de acesso na APS.",
        "apis": ["dadosabertos_mt_assentamentos_intermt"],
    })


# Migração v27 — Dados Abertos MT / INTERMAT — Terras Indígenas.
# Camada territorial de equidade para povos indígenas, acesso geográfico e priorização APS.
if not any(item.get("codigo") == "dadosabertos_mt_terras_indigenas_intermt" for item in API_CATALOG):
    API_CATALOG.append({
        "codigo": "dadosabertos_mt_terras_indigenas_intermt",
        "grupo": "Dados Abertos MT / INTERMAT",
        "nome": "Terras Indígenas — INTERMAT/MT",
        "descricao": "Carrega a camada estadual de terras indígenas publicada no Portal de Dados Abertos MT. A base é territorial e serve para análises de equidade, populações tradicionais, vazios assistenciais e planejamento da APS em áreas de difícil acesso.",
        "funcao_carregar": "carregar_terras_indigenas_intermt_mt",
        "funcao_testar": "testar_terras_indigenas_intermt_mt",
        "tipo_base": "dados_mt_terras_indigenas",
        "status_migracao": "Migração v27: conector nativo API-only para ZIP/SHP do INTERMAT; importa tabela própria, sem entrar automaticamente na Base Completa.",
        "executor": "nativo",
        "fallback_legacy": False,
        "modulo_nativo": "services.api_dadosabertos_mt_terras_indigenas",
        "funcao_nativa": "carregar_terras_indigenas_intermt_mt",
    })

if not any(item.get("codigo") == "bloco_dadosabertos_mt_terras_indigenas" for item in API_BLOCKS):
    API_BLOCKS.append({
        "codigo": "bloco_dadosabertos_mt_terras_indigenas",
        "nome": "Dados Abertos MT / INTERMAT — Terras Indígenas",
        "descricao": "Cria camada territorial estadual de terras indígenas para análise de equidade, vulnerabilidade territorial e dificuldade de acesso na APS.",
        "apis": ["dadosabertos_mt_terras_indigenas_intermt"],
    })


# Patch: Dados Abertos MT / SEMA — Gestão de Áreas Contaminadas
if not any(item.get("codigo") == "dadosabertos_mt_areas_contaminadas_sema" for item in API_CATALOG):
    API_CATALOG.append({
        "codigo": "dadosabertos_mt_areas_contaminadas_sema",
        "grupo": "Dados Abertos MT",
        "nome": "SEMA — Gestão de Áreas Contaminadas",
        "descricao": "Carrega a base estadual de gestão de áreas contaminadas/acidentes com resíduos perigosos publicada no Portal de Dados Abertos MT. Camada ambiental de apoio à leitura de risco territorial e determinantes ambientais da APS.",
        "funcao_carregar": "carregar_areas_contaminadas_sema_mt",
        "funcao_testar": "testar_areas_contaminadas_sema_mt",
        "tipo_base": "dados_mt_areas_contaminadas",
        "status_migracao": "Camada estadual ambiental — API/arquivo público XLSX via Dados Abertos MT",
        "executor": "nativo",
        "fallback_legacy": False,
        "modulo_nativo": "services.api_dadosabertos_mt_areas_contaminadas",
        "funcao_nativa": "carregar_areas_contaminadas_sema_mt",
    })

if not any(item.get("codigo") == "bloco_dadosabertos_mt_areas_contaminadas" for item in API_BLOCKS):
    API_BLOCKS.append({
        "codigo": "bloco_dadosabertos_mt_areas_contaminadas",
        "nome": "Dados Abertos MT / SEMA — Áreas contaminadas",
        "descricao": "Cria camada ambiental estadual de áreas contaminadas/acidentes com resíduos perigosos para apoiar análises de risco territorial, vulnerabilidade ambiental e planejamento da APS.",
        "apis": ["dadosabertos_mt_areas_contaminadas_sema"],
        "ordem": 93,
    })


# Patch: Dados Abertos MT / SEMA — Compensação Ambiental
if not any(item.get("codigo") == "dadosabertos_mt_compensacao_ambiental_sema" for item in API_CATALOG):
    API_CATALOG.append({
        "codigo": "dadosabertos_mt_compensacao_ambiental_sema",
        "grupo": "Dados Abertos MT",
        "nome": "SEMA — Compensação Ambiental",
        "descricao": "Carrega a base estadual de compensação ambiental publicada no Portal de Dados Abertos MT. Camada ambiental complementar para análise territorial, investimentos/obrigações ambientais e determinantes ambientais relacionados à APS.",
        "funcao_carregar": "carregar_compensacao_ambiental_sema_mt",
        "funcao_testar": "testar_compensacao_ambiental_sema_mt",
        "tipo_base": "dados_mt_compensacao_ambiental",
        "status_migracao": "Camada estadual ambiental — arquivo público XLSX via Dados Abertos MT",
        "executor": "nativo",
        "fallback_legacy": False,
        "modulo_nativo": "services.api_dadosabertos_mt_compensacao_ambiental",
        "funcao_nativa": "carregar_compensacao_ambiental_sema_mt",
    })

if not any(item.get("codigo") == "bloco_dadosabertos_mt_compensacao_ambiental" for item in API_BLOCKS):
    API_BLOCKS.append({
        "codigo": "bloco_dadosabertos_mt_compensacao_ambiental",
        "nome": "Dados Abertos MT / SEMA — Compensação Ambiental",
        "descricao": "Cria camada estadual de compensação ambiental para apoiar leituras territoriais, ambientais e de vulnerabilidade na APS.",
        "apis": ["dadosabertos_mt_compensacao_ambiental_sema"],
        "ordem": 94,
    })

# Migração v35 — IBGE/SIDRA — Determinantes sociais básicos do Censo 2022.
# Água, esgoto, lixo, alfabetização/analfabetismo e nível de instrução em formato longo de indicadores municipais.
if not any(item.get("codigo") == "ibge_determinantes_sociais_basicos_2022" for item in API_CATALOG):
    API_CATALOG.append({
        "codigo": "ibge_determinantes_sociais_basicos_2022",
        "grupo": "IBGE/SIDRA — Determinantes sociais",
        "nome": "Determinantes sociais básicos — água, esgoto e educação",
        "descricao": "Carrega indicadores municipais do Censo 2022 relacionados a abastecimento de água, esgotamento sanitário, lixo, alfabetização/analfabetismo e nível de instrução, quando disponíveis nas tabelas SIDRA.",
        "funcao_carregar": "carregar_determinantes_sociais_basicos_ibge",
        "funcao_testar": "testar_determinantes_sociais_basicos_ibge",
        "tipo_base": "indicadores",
        "status_migracao": "Migração v35: conector nativo SIDRA/Censo 2022 para determinantes sociais básicos; grava em indicadores_municipais.",
        "executor": "nativo",
        "fallback_legacy": False,
        "modulo_nativo": "services.api_ibge_determinantes_sociais",
        "funcao_nativa": "carregar_determinantes_sociais_basicos_ibge",
    })

if not any(item.get("codigo") == "bloco_ibge_determinantes_sociais_basicos" for item in API_BLOCKS):
    API_BLOCKS.append({
        "codigo": "bloco_ibge_determinantes_sociais_basicos",
        "nome": "IBGE/SIDRA — Determinantes sociais básicos",
        "descricao": "Carrega indicadores sociais básicos do Censo 2022 para qualificar a análise social da APS: água, esgoto, lixo, alfabetização/analfabetismo e nível de instrução.",
        "apis": ["ibge_determinantes_sociais_basicos_2022"],
        "ordem": 35,
    })
