"""Catálogo institucional dos indicadores do Sistema de Inteligência APS.

Este arquivo não executa cálculos do sistema. Ele documenta, de forma padronizada,
os indicadores usados nas telas executivas, territoriais e municipais, ajudando a
explicar finalidade, fonte, interpretação, confiabilidade e limitações.
"""

from __future__ import annotations

INDICADORES_CATALOGO = [
    {
        "eixo": "Capacidade instalada APS",
        "indicador": "Total de UBS / estabelecimentos APS",
        "campo_sistema": "total_ubs",
        "finalidade": "Mensurar a infraestrutura física de referência para atenção primária no município.",
        "formula": "Contagem de estabelecimentos APS/UBS vinculados ao município na base consolidada.",
        "fonte": "CNES / base municipal consolidada do sistema.",
        "interpretacao": "Quanto maior o número, maior a capacidade física potencial. A leitura deve ser cruzada com população, distribuição territorial e equipes.",
        "confiabilidade": "Consolidado",
        "periodicidade": "Conforme atualização da base CNES/local.",
        "limitacoes": "Não confirma horário de funcionamento, estrutura física real, carteira de serviços, qualidade da unidade ou capacidade efetiva de atendimento.",
        "uso_recomendado": "Comparar pressão populacional por UBS e apoiar estudos de expansão, reforma ou reorganização territorial.",
        "direcao": "Maior tende a ser melhor, mas depende do porte populacional e distribuição territorial.",
        "peso_score": "Base para fragilidade de capacidade e pressão territorial.",
    },
    {
        "eixo": "Capacidade instalada APS",
        "indicador": "Total de equipes APS",
        "campo_sistema": "total_equipes_aps",
        "finalidade": "Mensurar a capacidade assistencial cadastrada por equipes da APS.",
        "formula": "Soma das equipes APS consideradas pelo sistema, especialmente códigos 70, 71, 72, 73, 74 e 76.",
        "fonte": "CNES/INE e base consolidada.",
        "interpretacao": "Indica capacidade assistencial cadastrada. Deve ser lido com população, profissionais vinculados e códigos de equipe.",
        "confiabilidade": "Consolidado",
        "periodicidade": "Conforme atualização CNES/INE.",
        "limitacoes": "Cadastro não garante atuação plena, carga horária real, equipe completa ou cobertura efetiva do território.",
        "uso_recomendado": "Avaliar suficiência de equipes e priorizar validação com ERS/município.",
        "direcao": "Maior tende a ser melhor, considerando população e necessidade territorial.",
        "peso_score": "Base para população por equipe e fragilidade de capacidade.",
    },
    {
        "eixo": "Capacidade instalada APS",
        "indicador": "Profissionais vinculados à APS",
        "campo_sistema": "total_profissionais_aps",
        "finalidade": "Acompanhar o volume de profissionais vinculados às equipes/unidades APS na base CNES.",
        "formula": "Contagem de vínculos profissionais encontrados nas bases CNES/INE do sistema.",
        "fonte": "CNES profissionais / vínculos por equipe ou estabelecimento.",
        "interpretacao": "Ajuda a verificar densidade de força de trabalho e possíveis inconsistências de equipe.",
        "confiabilidade": "Consolidado",
        "periodicidade": "Conforme atualização CNES.",
        "limitacoes": "Pode conter duplicidade de vínculos, inconsistência de carga horária ou defasagem cadastral.",
        "uso_recomendado": "Auditar capacidade da APS e apoiar leitura dos códigos de equipes por município.",
        "direcao": "Maior tende a indicar maior capacidade, mas deve ser interpretado com vínculos, carga horária e população.",
        "peso_score": "Base para profissionais por equipe e fragilidade de capacidade.",
    },
    {
        "eixo": "Pressão assistencial",
        "indicador": "População por equipe APS",
        "campo_sistema": "populacao_por_equipe",
        "finalidade": "Estimar a pressão populacional potencial sobre as equipes APS cadastradas.",
        "formula": "população municipal ÷ total de equipes APS.",
        "fonte": "IBGE/base municipal consolidada + CNES/INE.",
        "interpretacao": "Quanto maior o valor, maior a pressão potencial sobre cada equipe. Valor elevado sugere necessidade de análise de expansão ou reorganização.",
        "confiabilidade": "Consolidado",
        "periodicidade": "Conforme atualização populacional e CNES.",
        "limitacoes": "Não representa adscrição real, microáreas, barreiras geográficas, demanda espontânea ou população flutuante.",
        "uso_recomendado": "Triagem de municípios com possível insuficiência de equipes APS.",
        "direcao": "Maior tende a ser pior.",
        "peso_score": "Componente central do vazio assistencial.",
    },
    {
        "eixo": "Pressão territorial",
        "indicador": "População por UBS / estabelecimento APS",
        "campo_sistema": "populacao_por_ubs",
        "finalidade": "Estimar a pressão populacional sobre a estrutura física de APS no município.",
        "formula": "população municipal ÷ total de UBS/estabelecimentos APS.",
        "fonte": "IBGE/base municipal consolidada + CNES estabelecimentos.",
        "interpretacao": "Valor elevado indica possível concentração de população por unidade e necessidade de olhar distribuição territorial.",
        "confiabilidade": "Consolidado",
        "periodicidade": "Conforme atualização populacional e CNES.",
        "limitacoes": "Não considera localização dentro do município, tamanho da unidade, horário de atendimento ou carteira de serviços.",
        "uso_recomendado": "Apoiar estudo de construção, ampliação, reforma ou redistribuição de UBS.",
        "direcao": "Maior tende a ser pior.",
        "peso_score": "Componente do vazio assistencial e da pressão territorial.",
    },
    {
        "eixo": "Vazio assistencial",
        "indicador": "Score de vazio assistencial",
        "campo_sistema": "score_vazio_assistencial",
        "finalidade": "Sintetizar pressão assistencial e territorial relacionada à oferta APS.",
        "formula": "Combinação normalizada de população por equipe, população por UBS e pressão APS em territórios mapeados.",
        "fonte": "Base consolidada, CNES, IBGE e camada territorial intramunicipal quando disponível.",
        "interpretacao": "Quanto maior o score, maior a necessidade de investigação sobre vazios assistenciais.",
        "confiabilidade": "Gerencial",
        "periodicidade": "Atualização conforme bases municipais, CNES e camadas territoriais.",
        "limitacoes": "É score de triagem, não indicador normativo oficial. Não substitui validação local, rota real, tempo de deslocamento ou adscrição das equipes.",
        "uso_recomendado": "Priorizar municípios/territórios para análise técnica, pactuação e validação regional.",
        "direcao": "Maior é pior/prioritário.",
        "peso_score": "Componente de maior peso no score integrado atual.",
    },
    {
        "eixo": "Vulnerabilidade social",
        "indicador": "Score de vulnerabilidade social",
        "campo_sistema": "score_vulnerabilidade_social",
        "finalidade": "Sintetizar condições sociais que podem ampliar risco sanitário e dificultar acesso à APS.",
        "formula": "Combinação normalizada de analfabetismo/baixa instrução, renda, saneamento e variáveis territoriais disponíveis.",
        "fonte": "IBGE/Censo, MDS/CadÚnico quando disponível e bases de referência do sistema.",
        "interpretacao": "Quanto maior o score, maior a necessidade de abordagem intersetorial, busca ativa e cuidado territorializado.",
        "confiabilidade": "Parcialmente consolidado",
        "periodicidade": "Depende da atualização de bases censitárias e socioassistenciais.",
        "limitacoes": "Algumas variáveis podem ter defasagem censitária, estimativas ou granularidade insuficiente para bairros oficiais.",
        "uso_recomendado": "Cruzar vulnerabilidade social com capacidade APS para identificar prioridade de apoio estadual.",
        "direcao": "Maior é pior/prioritário.",
        "peso_score": "Componente social do score integrado.",
    },
    {
        "eixo": "Capacidade instalada APS",
        "indicador": "Score de fragilidade de capacidade",
        "campo_sistema": "score_fragilidade_capacidade",
        "finalidade": "Identificar municípios com menor densidade relativa de equipes, UBS e profissionais.",
        "formula": "Combinação normalizada e invertida de equipes por 10 mil habitantes, UBS por 10 mil habitantes e profissionais por equipe.",
        "fonte": "Base municipal consolidada, CNES/INE e profissionais CNES.",
        "interpretacao": "Quanto maior o score, maior a fragilidade relativa da capacidade instalada.",
        "confiabilidade": "Gerencial",
        "periodicidade": "Conforme atualização CNES e base municipal.",
        "limitacoes": "Não substitui análise de qualidade da equipe, composição profissional, carga horária e processo de trabalho.",
        "uso_recomendado": "Apoiar decisões de reforço de equipes, qualificação cadastral e reorganização da rede APS.",
        "direcao": "Maior é pior/prioritário.",
        "peso_score": "Componente relevante do score integrado.",
    },
    {
        "eixo": "Equidade territorial",
        "indicador": "Score de equidade territorial",
        "campo_sistema": "score_equidade_territorial",
        "finalidade": "Sinalizar municípios com camadas territoriais especiais que exigem atenção diferenciada.",
        "formula": "Combinação de registros de terras indígenas, assentamentos, áreas contaminadas e territórios com alta pressão APS.",
        "fonte": "Dados Abertos MT, bases territoriais de referência e camada intramunicipal.",
        "interpretacao": "Quanto maior o score, maior a necessidade de abordagem sensível à equidade e às especificidades territoriais.",
        "confiabilidade": "Parcialmente consolidado",
        "periodicidade": "Conforme atualização das camadas territoriais.",
        "limitacoes": "A existência de registro territorial não mede automaticamente população afetada, acesso real ou necessidade assistencial individual.",
        "uso_recomendado": "Priorizar validação qualitativa e planejamento de ações diferenciadas em territórios especiais.",
        "direcao": "Maior é mais prioritário.",
        "peso_score": "Componente de equidade do score integrado.",
    },
    {
        "eixo": "Prioridade integrada",
        "indicador": "Score de prioridade integrada APS",
        "campo_sistema": "score_prioridade_integrada",
        "finalidade": "Organizar uma régua executiva de priorização para tomada de decisão estadual.",
        "formula": "Combinação ponderada de vazio assistencial, vulnerabilidade social, fragilidade da capacidade instalada e equidade territorial.",
        "fonte": "Indicadores derivados do próprio sistema, com base em IBGE, CNES, MDS e camadas territoriais.",
        "interpretacao": "Quanto maior o score, maior a prioridade para investigação técnica, validação regional e eventual intervenção estadual.",
        "confiabilidade": "Gerencial",
        "periodicidade": "Recalculado conforme atualização das bases.",
        "limitacoes": "Não é indicador oficial de financiamento ou habilitação. Deve ser usado como ferramenta de inteligência, não como decisão automática.",
        "uso_recomendado": "Ranking, triagem, despacho técnico, reuniões regionais e priorização de estudos de UBS/equipes.",
        "direcao": "Maior é mais prioritário.",
        "peso_score": "Resultado final de priorização gerencial.",
    },
    {
        "eixo": "Georreferenciamento",
        "indicador": "Distância até UBS/APS mais próxima",
        "campo_sistema": "distancia_km / distancia_ubs_km",
        "finalidade": "Identificar territórios com possível dificuldade física de acesso à APS.",
        "formula": "Distância geográfica entre ponto territorial e UBS/estabelecimento APS mais próximo.",
        "fonte": "Camada territorial intramunicipal + coordenadas de UBS/estabelecimentos.",
        "interpretacao": "Distâncias maiores sugerem potencial vazio geográfico, principalmente se associadas a vulnerabilidade e baixa capacidade APS.",
        "confiabilidade": "Parcialmente consolidado",
        "periodicidade": "Conforme atualização de coordenadas e camadas territoriais.",
        "limitacoes": "Distância em linha reta/geográfica não representa rota viária, tempo de deslocamento, sazonalidade, transporte público ou barreiras naturais.",
        "uso_recomendado": "Triagem territorial inicial para estudos de vazios assistenciais e planejamento de visitas técnicas.",
        "direcao": "Maior é pior/prioritário.",
        "peso_score": "Deve compor evolução futura do vazio assistencial integrado.",
    },
    {
        "eixo": "Qualidade da base",
        "indicador": "Status de confiabilidade da fonte",
        "campo_sistema": "status_fonte / classificacao_fonte",
        "finalidade": "Indicar se uma fonte está consolidada, parcial, experimental, não funcional ou a substituir.",
        "formula": "Classificação técnico-gerencial definida a partir de disponibilidade, utilidade, estabilidade e aderência ao objetivo do sistema.",
        "fonte": "Governança interna do sistema.",
        "interpretacao": "Ajuda o usuário a entender se o dado pode sustentar decisão ou apenas análise exploratória.",
        "confiabilidade": "Governança",
        "periodicidade": "Sempre que novas fontes forem testadas ou substituídas.",
        "limitacoes": "Classificação depende de curadoria técnica e deve ser revisada com a equipe responsável.",
        "uso_recomendado": "Separar painéis executivos de experimentos técnicos e evitar conclusões indevidas.",
        "direcao": "Não se aplica.",
        "peso_score": "Não compõe score; orienta interpretação.",
    },
]

FONTES_CATALOGO = [
    {"grupo": "Consolidada", "fonte": "IBGE territorial/populacional", "uso": "Municípios, população, área, densidade e bases censitárias", "status": "Consolidada", "observacao": "Base estrutural para população e leitura territorial."},
    {"grupo": "Consolidada", "fonte": "CNES/INE — equipes APS", "uso": "Equipes e códigos 70, 71, 72, 73, 74 e 76", "status": "Consolidada", "observacao": "Essencial para capacidade APS e profissionais."},
    {"grupo": "Consolidada", "fonte": "CNES — estabelecimentos", "uso": "UBS/estabelecimentos APS e coordenadas quando disponíveis", "status": "Consolidada", "observacao": "Requer auditoria de coordenadas e tipo de estabelecimento."},
    {"grupo": "Consolidada", "fonte": "MDS / CadÚnico / Bolsa Família / BPC", "uso": "Vulnerabilidade socioassistencial", "status": "Consolidada", "observacao": "Boa fonte para cruzamentos sociais quando disponível na granularidade adequada."},
    {"grupo": "Consolidada", "fonte": "Regionalização MS", "uso": "Regiões de Saúde e leitura tática", "status": "Consolidada", "observacao": "Organiza análise por pactuação regional."},
    {"grupo": "Parcial", "fonte": "INEP / Censo Escolar", "uso": "Educação, alfabetização e escolaridade", "status": "Parcialmente funcional", "observacao": "Útil, mas precisa validação de granularidade e aderência ao painel."},
    {"grupo": "Parcial", "fonte": "IBGE Censo 2022 — instrução, renda e saneamento", "uso": "Determinantes sociais", "status": "Parcialmente funcional", "observacao": "Algumas consultas podem exigir tratamento específico por tabela/variável."},
    {"grupo": "Parcial", "fonte": "Dados Abertos MT — assentamentos e terras indígenas", "uso": "Camadas territoriais especiais", "status": "Parcialmente funcional", "observacao": "Boa para equidade territorial, mas não substitui validação populacional/local."},
    {"grupo": "Experimental", "fonte": "IPEA / IVS", "uso": "Vulnerabilidade social", "status": "Experimental", "observacao": "Testes anteriores não retornaram dados municipais úteis para MT em alguns cenários."},
    {"grupo": "Experimental", "fonte": "PNI", "uso": "Imunização", "status": "Experimental/frágil", "observacao": "Pode sofrer bloqueio de acesso ou exigir fonte alternativa."},
    {"grupo": "Experimental", "fonte": "SIA/SIH Tabnet", "uso": "Produção ambulatorial/hospitalar", "status": "Experimental", "observacao": "Potencial alto, mas exige carga e modelagem mais pesada."},
    {"grupo": "A substituir", "fonte": "Bairros/localidades oficiais", "uso": "Georreferenciamento intramunicipal", "status": "A substituir futuramente", "observacao": "Hoje o sistema usa bairros/localidades/setores como aproximação territorial; ideal evoluir para base municipal oficial validada."},
    {"grupo": "A substituir", "fonte": "Rotas reais até UBS", "uso": "Tempo/distância de deslocamento", "status": "A substituir futuramente", "observacao": "Distância atual não representa rota viária; evolução futura deve calcular tempo real de acesso."},
]

PESOS_SCORE_ATUAL = [
    {"componente": "Vazio assistencial", "peso": 35, "descricao": "Pressão populacional por equipe, por UBS e pressão APS territorial."},
    {"componente": "Vulnerabilidade social", "peso": 25, "descricao": "Educação, renda, saneamento e fragilidades sociais disponíveis."},
    {"componente": "Fragilidade de capacidade", "peso": 25, "descricao": "Densidade relativa de equipes, UBS e profissionais."},
    {"componente": "Equidade territorial", "peso": 15, "descricao": "Territórios especiais e camadas de atenção diferenciada."},
]

CLASSES_PRIORIDADE = [
    {"classe": "Prioridade crítica", "criterio": "Score >= 75", "uso": "Análise imediata, validação regional e possível despacho de intervenção."},
    {"classe": "Alta prioridade", "criterio": "Score >= 60 e < 75", "uso": "Pactuação regional, qualificação cadastral e estudo de expansão/reorganização."},
    {"classe": "Monitoramento intensivo", "criterio": "Score >= 45 e < 60", "uso": "Acompanhamento técnico e investigação de componentes específicos."},
    {"classe": "Monitoramento regular", "criterio": "Score < 45", "uso": "Acompanhamento ordinário e validação periódica da base."},
]
