DEFAULT_MUNICIPIOS = [
    # 1 - Baixada Cuiabana
    {"municipio": "Cuiabá", "regiao_saude": "Baixada Cuiabana", "escritorio_regional": "Cuiabá", "porte": ""},
    {"municipio": "Acorizal", "regiao_saude": "Baixada Cuiabana", "escritorio_regional": "Cuiabá", "porte": ""},
    {"municipio": "Barão de Melgaço", "regiao_saude": "Baixada Cuiabana", "escritorio_regional": "Cuiabá", "porte": ""},
    {"municipio": "Chapada dos Guimarães", "regiao_saude": "Baixada Cuiabana", "escritorio_regional": "Cuiabá", "porte": ""},
    {"municipio": "Jangada", "regiao_saude": "Baixada Cuiabana", "escritorio_regional": "Cuiabá", "porte": ""},
    {"municipio": "Nova Brasilândia", "regiao_saude": "Baixada Cuiabana", "escritorio_regional": "Cuiabá", "porte": ""},
    {"municipio": "Nossa Senhora do Livramento", "regiao_saude": "Baixada Cuiabana", "escritorio_regional": "Cuiabá", "porte": ""},
    {"municipio": "Planalto da Serra", "regiao_saude": "Baixada Cuiabana", "escritorio_regional": "Cuiabá", "porte": ""},
    {"municipio": "Poconé", "regiao_saude": "Baixada Cuiabana", "escritorio_regional": "Cuiabá", "porte": ""},
    {"municipio": "Santo Antônio do Leverger", "regiao_saude": "Baixada Cuiabana", "escritorio_regional": "Cuiabá", "porte": ""},
    {"municipio": "Várzea Grande", "regiao_saude": "Baixada Cuiabana", "escritorio_regional": "Cuiabá", "porte": ""},

    # 2 - Região Sul
    {"municipio": "Rondonópolis", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Alto Araguaia", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Alto Garças", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Alto Taquari", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Araguainha", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Campo Verde", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Dom Aquino", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Guiratinga", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Itiquira", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Jaciara", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Juscimeira", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Paranatinga", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Pedra Preta", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Poxoréu", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Primavera do Leste", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Santo Antônio do Leste", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "São José do Povo", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "São Pedro da Cipa", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},
    {"municipio": "Tesouro", "regiao_saude": "Região Sul", "escritorio_regional": "Rondonópolis", "porte": ""},

    # 3 - Garças Araguaia
    {"municipio": "Barra do Garças", "regiao_saude": "Garças Araguaia", "escritorio_regional": "Barra do Garças", "porte": ""},
    {"municipio": "Araguaiana", "regiao_saude": "Garças Araguaia", "escritorio_regional": "Barra do Garças", "porte": ""},
    {"municipio": "Campinápolis", "regiao_saude": "Garças Araguaia", "escritorio_regional": "Barra do Garças", "porte": ""},
    {"municipio": "General Carneiro", "regiao_saude": "Garças Araguaia", "escritorio_regional": "Barra do Garças", "porte": ""},
    {"municipio": "Nova Xavantina", "regiao_saude": "Garças Araguaia", "escritorio_regional": "Barra do Garças", "porte": ""},
    {"municipio": "Novo São Joaquim", "regiao_saude": "Garças Araguaia", "escritorio_regional": "Barra do Garças", "porte": ""},
    {"municipio": "Pontal do Araguaia", "regiao_saude": "Garças Araguaia", "escritorio_regional": "Barra do Garças", "porte": ""},
    {"municipio": "Ponte Branca", "regiao_saude": "Garças Araguaia", "escritorio_regional": "Barra do Garças", "porte": ""},
    {"municipio": "Ribeirãozinho", "regiao_saude": "Garças Araguaia", "escritorio_regional": "Barra do Garças", "porte": ""},
    {"municipio": "Torixoréu", "regiao_saude": "Garças Araguaia", "escritorio_regional": "Barra do Garças", "porte": ""},

    # 4 - Oeste
    {"municipio": "Cáceres", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},
    {"municipio": "Araputanga", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},
    {"municipio": "Curvelândia", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},
    {"municipio": "Glória D'Oeste", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},
    {"municipio": "Indiavaí", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},
    {"municipio": "Jauru", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},
    {"municipio": "Mirassol D'Oeste", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},
    {"municipio": "Porto Esperidião", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},
    {"municipio": "Reserva do Cabaçal", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},
    {"municipio": "Rio Branco", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},
    {"municipio": "Salto do Céu", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},
    {"municipio": "São José dos Quatro Marcos", "regiao_saude": "Oeste", "escritorio_regional": "Cáceres", "porte": ""},

    # 5 - Noroeste
    {"municipio": "Juína", "regiao_saude": "Noroeste", "escritorio_regional": "Juína", "porte": ""},
    {"municipio": "Aripuanã", "regiao_saude": "Noroeste", "escritorio_regional": "Juína", "porte": ""},
    {"municipio": "Brasnorte", "regiao_saude": "Noroeste", "escritorio_regional": "Juína", "porte": ""},
    {"municipio": "Castanheira", "regiao_saude": "Noroeste", "escritorio_regional": "Juína", "porte": ""},
    {"municipio": "Colniza", "regiao_saude": "Noroeste", "escritorio_regional": "Juína", "porte": ""},
    {"municipio": "Cotriguaçu", "regiao_saude": "Noroeste", "escritorio_regional": "Juína", "porte": ""},
    {"municipio": "Juruena", "regiao_saude": "Noroeste", "escritorio_regional": "Juína", "porte": ""},

    # 6 - Araguaia Xingu
    {"municipio": "Porto Alegre do Norte", "regiao_saude": "Araguaia Xingu", "escritorio_regional": "Porto Alegre do Norte", "porte": ""},
    {"municipio": "Canabrava do Norte", "regiao_saude": "Araguaia Xingu", "escritorio_regional": "Porto Alegre do Norte", "porte": ""},
    {"municipio": "Confresa", "regiao_saude": "Araguaia Xingu", "escritorio_regional": "Porto Alegre do Norte", "porte": ""},
    {"municipio": "Santa Cruz do Xingu", "regiao_saude": "Araguaia Xingu", "escritorio_regional": "Porto Alegre do Norte", "porte": ""},
    {"municipio": "Santa Terezinha", "regiao_saude": "Araguaia Xingu", "escritorio_regional": "Porto Alegre do Norte", "porte": ""},
    {"municipio": "São José do Xingu", "regiao_saude": "Araguaia Xingu", "escritorio_regional": "Porto Alegre do Norte", "porte": ""},
    {"municipio": "Vila Rica", "regiao_saude": "Araguaia Xingu", "escritorio_regional": "Porto Alegre do Norte", "porte": ""},

    # 7 - Teles Pires
    {"municipio": "Sinop", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Cláudia", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Feliz Natal", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Ipiranga do Norte", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Itanhangá", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Lucas do Rio Verde", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Nova Mutum", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Nova Ubiratã", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Santa Carmem", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Santa Rita do Trivelato", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Sorriso", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Tapurah", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "União do Sul", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Vera", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},
    {"municipio": "Boa Esperança do Norte", "regiao_saude": "Teles Pires", "escritorio_regional": "Sinop", "porte": ""},

    # 8 - Médio Norte
    {"municipio": "Tangará da Serra", "regiao_saude": "Médio Norte", "escritorio_regional": "Tangará da Serra", "porte": ""},
    {"municipio": "Arenápolis", "regiao_saude": "Médio Norte", "escritorio_regional": "Tangará da Serra", "porte": ""},
    {"municipio": "Barra do Bugres", "regiao_saude": "Médio Norte", "escritorio_regional": "Tangará da Serra", "porte": ""},
    {"municipio": "Campo Novo do Parecis", "regiao_saude": "Médio Norte", "escritorio_regional": "Tangará da Serra", "porte": ""},
    {"municipio": "Denise", "regiao_saude": "Médio Norte", "escritorio_regional": "Tangará da Serra", "porte": ""},
    {"municipio": "Nova Marilândia", "regiao_saude": "Médio Norte", "escritorio_regional": "Tangará da Serra", "porte": ""},
    {"municipio": "Nova Olímpia", "regiao_saude": "Médio Norte", "escritorio_regional": "Tangará da Serra", "porte": ""},
    {"municipio": "Porto Estrela", "regiao_saude": "Médio Norte", "escritorio_regional": "Tangará da Serra", "porte": ""},
    {"municipio": "Santo Afonso", "regiao_saude": "Médio Norte", "escritorio_regional": "Tangará da Serra", "porte": ""},
    {"municipio": "Sapezal", "regiao_saude": "Médio Norte", "escritorio_regional": "Tangará da Serra", "porte": ""},

    # 9 - Centro Norte
    {"municipio": "Diamantino", "regiao_saude": "Centro Norte", "escritorio_regional": "Diamantino", "porte": ""},
    {"municipio": "Alto Paraguai", "regiao_saude": "Centro Norte", "escritorio_regional": "Diamantino", "porte": ""},
    {"municipio": "Nobres", "regiao_saude": "Centro Norte", "escritorio_regional": "Diamantino", "porte": ""},
    {"municipio": "Nortelândia", "regiao_saude": "Centro Norte", "escritorio_regional": "Diamantino", "porte": ""},
    {"municipio": "Nova Maringá", "regiao_saude": "Centro Norte", "escritorio_regional": "Diamantino", "porte": ""},
    {"municipio": "Rosário Oeste", "regiao_saude": "Centro Norte", "escritorio_regional": "Diamantino", "porte": ""},
    {"municipio": "São José do Rio Claro", "regiao_saude": "Centro Norte", "escritorio_regional": "Diamantino", "porte": ""},

    # 10 - Alto Tapajós
    {"municipio": "Alta Floresta", "regiao_saude": "Alto Tapajós", "escritorio_regional": "Alta Floresta", "porte": ""},
    {"municipio": "Apiacás", "regiao_saude": "Alto Tapajós", "escritorio_regional": "Alta Floresta", "porte": ""},
    {"municipio": "Carlinda", "regiao_saude": "Alto Tapajós", "escritorio_regional": "Alta Floresta", "porte": ""},
    {"municipio": "Nova Bandeirantes", "regiao_saude": "Alto Tapajós", "escritorio_regional": "Alta Floresta", "porte": ""},
    {"municipio": "Nova Monte Verde", "regiao_saude": "Alto Tapajós", "escritorio_regional": "Alta Floresta", "porte": ""},
    {"municipio": "Paranaíta", "regiao_saude": "Alto Tapajós", "escritorio_regional": "Alta Floresta", "porte": ""},

    # 11 - Vale do Arinos
    {"municipio": "Juara", "regiao_saude": "Vale do Arinos", "escritorio_regional": "Juara", "porte": ""},
    {"municipio": "Novo Horizonte do Norte", "regiao_saude": "Vale do Arinos", "escritorio_regional": "Juara", "porte": ""},
    {"municipio": "Porto dos Gaúchos", "regiao_saude": "Vale do Arinos", "escritorio_regional": "Juara", "porte": ""},
    {"municipio": "Tabaporã", "regiao_saude": "Vale do Arinos", "escritorio_regional": "Juara", "porte": ""},

    # 12 - Vale do Peixoto
    {"municipio": "Peixoto de Azevedo", "regiao_saude": "Vale do Peixoto", "escritorio_regional": "Peixoto de Azevedo", "porte": ""},
    {"municipio": "Guarantã do Norte", "regiao_saude": "Vale do Peixoto", "escritorio_regional": "Peixoto de Azevedo", "porte": ""},
    {"municipio": "Matupá", "regiao_saude": "Vale do Peixoto", "escritorio_regional": "Peixoto de Azevedo", "porte": ""},
    {"municipio": "Novo Mundo", "regiao_saude": "Vale do Peixoto", "escritorio_regional": "Peixoto de Azevedo", "porte": ""},
    {"municipio": "Terra Nova do Norte", "regiao_saude": "Vale do Peixoto", "escritorio_regional": "Peixoto de Azevedo", "porte": ""},

    # 13 - Médio Araguaia
    {"municipio": "Água Boa", "regiao_saude": "Médio Araguaia", "escritorio_regional": "Água Boa", "porte": ""},
    {"municipio": "Bom Jesus do Araguaia", "regiao_saude": "Médio Araguaia", "escritorio_regional": "Água Boa", "porte": ""},
    {"municipio": "Canarana", "regiao_saude": "Médio Araguaia", "escritorio_regional": "Água Boa", "porte": ""},
    {"municipio": "Cocalinho", "regiao_saude": "Médio Araguaia", "escritorio_regional": "Água Boa", "porte": ""},
    {"municipio": "Nova Nazaré", "regiao_saude": "Médio Araguaia", "escritorio_regional": "Água Boa", "porte": ""},
    {"municipio": "Gaúcha do Norte", "regiao_saude": "Médio Araguaia", "escritorio_regional": "Água Boa", "porte": ""},
    {"municipio": "Querência", "regiao_saude": "Médio Araguaia", "escritorio_regional": "Água Boa", "porte": ""},
    {"municipio": "Ribeirão Cascalheira", "regiao_saude": "Médio Araguaia", "escritorio_regional": "Água Boa", "porte": ""},

    # 14 - Vale do Guaporé
    {"municipio": "Pontes e Lacerda", "regiao_saude": "Vale do Guaporé", "escritorio_regional": "Pontes e Lacerda", "porte": ""},
    {"municipio": "Campos de Júlio", "regiao_saude": "Vale do Guaporé", "escritorio_regional": "Pontes e Lacerda", "porte": ""},
    {"municipio": "Comodoro", "regiao_saude": "Vale do Guaporé", "escritorio_regional": "Pontes e Lacerda", "porte": ""},
    {"municipio": "Conquista D'Oeste", "regiao_saude": "Vale do Guaporé", "escritorio_regional": "Pontes e Lacerda", "porte": ""},
    {"municipio": "Figueirópolis D'Oeste", "regiao_saude": "Vale do Guaporé", "escritorio_regional": "Pontes e Lacerda", "porte": ""},
    {"municipio": "Nova Lacerda", "regiao_saude": "Vale do Guaporé", "escritorio_regional": "Pontes e Lacerda", "porte": ""},
    {"municipio": "Rondolândia", "regiao_saude": "Vale do Guaporé", "escritorio_regional": "Pontes e Lacerda", "porte": ""},
    {"municipio": "Vale de São Domingos", "regiao_saude": "Vale do Guaporé", "escritorio_regional": "Pontes e Lacerda", "porte": ""},
    {"municipio": "Vila Bela da Santíssima Trindade", "regiao_saude": "Vale do Guaporé", "escritorio_regional": "Pontes e Lacerda", "porte": ""},

    # 15 - Região Norte
    {"municipio": "Colíder", "regiao_saude": "Região Norte", "escritorio_regional": "Colíder", "porte": ""},
    {"municipio": "Itaúba", "regiao_saude": "Região Norte", "escritorio_regional": "Colíder", "porte": ""},
    {"municipio": "Marcelândia", "regiao_saude": "Região Norte", "escritorio_regional": "Colíder", "porte": ""},
    {"municipio": "Nova Canaã do Norte", "regiao_saude": "Região Norte", "escritorio_regional": "Colíder", "porte": ""},
    {"municipio": "Nova Guarita", "regiao_saude": "Região Norte", "escritorio_regional": "Colíder", "porte": ""},
    {"municipio": "Nova Santa Helena", "regiao_saude": "Região Norte", "escritorio_regional": "Colíder", "porte": ""},

    # 16 - Norte Araguaia Karajá
    {"municipio": "São Félix do Araguaia", "regiao_saude": "Norte Araguaia Karajá", "escritorio_regional": "São Félix do Araguaia", "porte": ""},
    {"municipio": "Alto Boa Vista", "regiao_saude": "Norte Araguaia Karajá", "escritorio_regional": "São Félix do Araguaia", "porte": ""},
    {"municipio": "Luciara", "regiao_saude": "Norte Araguaia Karajá", "escritorio_regional": "São Félix do Araguaia", "porte": ""},
    {"municipio": "Novo Santo Antônio", "regiao_saude": "Norte Araguaia Karajá", "escritorio_regional": "São Félix do Araguaia", "porte": ""},
    {"municipio": "Serra Nova Dourada", "regiao_saude": "Norte Araguaia Karajá", "escritorio_regional": "São Félix do Araguaia", "porte": ""},
]